Algoritmo "AreaQuadrado"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Ler as dimensões de um quadrado e mostrar o valor da sua área
// Autor(a)    : João Victor Oliveira Arruda
// Data atual  : 25/08/2021
Var
// Seção de Declarações das variáveis
lado, area: real

Inicio

Escreva("Digite o valor do lado do quadrado: ")
leia(lado)

Escreval("Área: ", quad(lado))

Fimalgoritmo